### ISSUE TITLE
Error when parsing a certificate with a URI SAN containing multiple colons

### ISSUE THREAD

**Issue by adammw** [pyca/service-identity#38]
We add a URI SAN to our certificates that contain multiple colons, for example:
```
$ openssl x509 -in cert.crt -noout -text
...
            X509v3 Subject Alternative Name:
                URI:arn:aws:ec2:us-west-2:12345678:instance/i-0123456789
```

When verifying the hostname of the certificate (actually being called by Datadog's TLS check), we get a `ValueError` exception since the code assumes only a single colon will be contained in the URI, and does not parse the URI correctly.

Partial Traceback:
```
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/service_identity/cryptography.py", line 59, in verify_certificate_hostname
          cert_patterns=extract_ids(certificate),
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/service_identity/cryptography.py", line 123, in extract_ids
          [
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/service_identity/cryptography.py", line 124, in <listcomp>
          URIPattern(uri.encode("utf-8"))
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/service_identity/_common.py", line 205, in __init__
          self.protocol_pattern, hostname = pattern.split(b":")
      ValueError: too many values to unpack (expected 2)
```

**Comment by sigmavirus24** [comment]
@adammw feel free to try out #39. Seemed like an easy fix so I threw it together

**Comment by hynek** [comment]
OK I have somewhat lost the overview…why was the PR opened and closed and what should happen here?

**Comment by sigmavirus24** [comment]
I opened it because it seemed like a quick and easy fix, and closed it because it wasn't clear if I was heading down the right track and I'm not personally affected, so I'm not bothered if nothing happens.

**Comment by AlexandreYang** [comment]
Looks like it's not just a parsing issue.

To support [Aws ARN format](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) we might need to add a `verify_certificate_arn` validator similar to existing `verify_certificate_ip_address` and verify_certificate_hostname: https://github.com/pyca/service-identity/blob/master/src/service_identity/cryptography.py#L38-L91

And corresponding ` ARN_ID` and  `ARNPattern` classes.

cc @hynek

**Comment by AlexandreYang** [comment]
> arn is not technically one of the forms supported in x509 SAN though, it's URI. It just so happens that this URI is an ARN.

Yes, true.

---

Note that, in the case of Datadog's TLS check, `verify_certificate_hostname` is used, which tries to [match a DNS (aka hostname)](https://github.com/pyca/service-identity/blob/c7aa7c0e3bab4bd73059ddf1579e12704de7017d/src/service_identity/cryptography.py#L60) not an URI. So even if the parsing succeed, the `verify_certificate_hostname` method will probably still fail since it's not meant to match ARN.

**Comment by hynek** [comment]
Could someone help me to find actionable items here please? 😅

**Comment by sigmavirus24** [comment]
> arn is not technically one of the forms supported in x509 SAN though, it's URI. It just so happens that this URI is an ARN.

ARNs aren't valid URIs per RFC 3986 depending on what you mean when you say it's a URI. The URI Matcher definitely is correct today as far as I can tell. I can't see how ARNs could be shoved in there without realzing the existing URI logic. I'd want to see if there are examples of a library like this one in go or other languages that handle ARNs appropriately without special casing them entirely

> Could someone help me to find actionable items here please? sweat_smile

I'm not sure there are any right no @hynek ... at least not aside from adding to the README/docs that ARNs aren't supported
