### ISSUE TITLE
consider tagging a new release

### ISSUE THREAD

**Issue by anthraxx** [pyca/service-identity#40]
Hi, the last release has been from 2018, which is quite old.
In the meanwhile the module canonical name has been renamed: https://github.com/pyca/service-identity/commit/4ebe1546204829878317b46334d012d6f474075d

Can this get a release?

**Comment by hynek** [comment]
There have been zero code changes since the last release. While there's been work all along to keep up with ecosystem best practices, I don't see the point of a release whose only visible change is a flip of `_` to `-` in the docs?

**Comment by hynek** [comment]
21.1 hit PyPI just now
